export const GET_ITEMS_BITSKINS='GET_ITEMS_BITSKINS';
export const GET_ITEMS_OPSKINS='GET_ITEMS_OPSKINS';
export const SEARCH_ITEM='SEARCH_ITEM';
export const ADD_TO_FAVS='ADD_TO_FAVS';
export const GET_FAV_ITEMS='GET_FAV_ITEMS';